# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Negotiator
tagline:          'Simple ad-blocking/privacy filter for advanced users'
description:      'Chrome Extension'
icon:             /images/icon128.png
url:              https://silentorbit.com/negotiator
baseurl:          /negotiator
email:		hello@silentorbit.com

author:
  name:           'Peter Hultqvist'
  url:            https://silentorbit.com/hultqvist/

license:
  url:		https://www.gnu.org/licenses/gpl-3.0
  title:	GPLv3

paginate:         5
paginate_path:    "/updates/page:num"

# Custom vars
version:          1.2.3

github:
  repo:           https://github.com/hultqvist/negotiator
  page:           https://github.com/hultqvist/negotiator/tree/gh-pages
  branch:         gh-pages
